
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnxlnsfzecldanhkgkpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBueGxuc2Z6ZWNsZGFuaGtna3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTE4NTUsImV4cCI6MjA2MzQyNzg1NX0.nymDNU3ceWisT4ZUelGgJ09JSFUxBt8Cu1QpN6W8X_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
    },
  }
});
